require 'Win32/Console/ANSI'   # windows only
require 'awesome_print'
require 'progressbar'
require 'htmlentities'
require './lib/card'
require './lib/deck.rb'
require './lib/display.rb'
require './lib/game.rb'
require './lib/gamestate.rb'
require './lib/house.rb'
require './lib/Menu.rb'
require './lib/player.rb'
require './lib/results.rb'
require './lib/ruleset.rb'
require './lib/shoe.rb'
require './lib/simulation.rb'
